import 'package:flutter/cupertino.dart';

class ContentAboutMe extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
        Text("PAGE 1"),
      ],
    );
  }
}