import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../widgets/widgets.dart';

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VerticalNavigation(
      navigationBackgroundColor: Colors.grey,
      pages: [
        VerticalNavigationItem(
            page: Column(
              children: [
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
              ],
            ),
            icon: Icon(Icons.home),
            iconTitle: "Mes compétences".toUpperCase()),
        VerticalNavigationItem(
          page: Column(
            children: [
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
              Text("PAGE 2"),
            ],
          ),
          icon: Icon(Icons.add),
          iconTitle: "Ceci est un très long texte qu'il faut forcement gérer"
        ),
        VerticalNavigationItem(
            page: Column(
              children: [
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
              ],
            ),
            icon: Icon(Icons.calendar_today)),
      ],
    );
  }
}
