import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../widgets/widgets.dart';

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VerticalNavigation(
      navigationBackgroundColor: Colors.lightGreen,
      pages: [
        VerticalNavigationItem(
            focusBackgroundColor: Colors.red,
            page: Column(
              children: [
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
                Text("PAGE 1"),
              ],
            ),
            icon: Icons.home,
            iconTitle: "Mes compétences".toUpperCase()),
        VerticalNavigationItem(
            focusIconColor: Colors.green,
            focusTextColor: Colors.greenAccent,
            page: Column(
              children: [
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
                Text("PAGE 2"),
              ],
            ),
            icon: Icons.add,
            iconTitle: "Ceci est un très long texte qu'il faut forcement gérer, vraiment très très long. Est-ce qu'une tarte à la créme en plus suffira ?"),
        VerticalNavigationItem(
            page: Column(
              children: [
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
                Text("PAGE 3"),
              ],
            ),
            icon: Icons.calendar_today),
      ],
    );
  }
}
